name: 'Gitops get and update state repo'
description: 'Get and update the state repository conposite-action'

runs:
  using: 'composite'
  steps:
    - name: get state repo
      uses: actions/checkout@master
      with:
        repository: ${{inputs.state-repository}}
        ref: ${{ inputs.branch-ref }}
        path: ./deploy-charts
        token: ${{ inputs.github-token }}
    - name: deploy to dev with updated update to dev state
      shell: bash
      run: |
        function update_state(){
           {
            git pull
            echo "./release git"
            ./release ${{inputs.release-type }} $(cut -d'/' -f2 <<<"${{inputs.project-repository}}") "${{inputs.project-repository}}" "${{ inputs.release-tag }}"
            git add chart
            git commit -am 'release to dev'
            git push
            return 0
           } || {
            git reset --hard dev
            return 1
           }
        }
        git config --global user.email "systemssupport@dummy.com"
        git config --global user.name "Actions Pipeline"
        cd ./deploy-charts
        pip install ruamel.yaml parse schema fire
        set -x
        for i in $(seq 1 5); do [ $i -gt 1 ] && update_state && sleep $(($RANDOM % 15)) && s=0 && break || s=$?; done; (exit $s)

inputs:
  github-token:
    description: 'Github Token'
    required: true
  state-repository:
    description: 'State repository'
    required: true
  branch-ref:
    description: 'Referenece Branch'
    required: true
  release-type:
    description: 'Define release type'
    required: true
  project-repository:
    description: 'Define the project repository.'
    required: true
  release-tag:
    description: "Release tag"
