name: 'Composite ECR Action'
description: 'Configures AWS credentials, logs in to ECR, and creates repository.'

runs:
  using: 'composite'
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:

        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{inputs.aws-secret-access-key}}
        aws-region: ${{ inputs.aws-region }}
        

    - name: Login to ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: tseting
      shell: bash
      run: |
        echo ${GITHUB_REPOSITORY}
    - name: Prep ECR repository
      uses: int128/create-ecr-repository-action@v1
      with:
        repository: ${{github.repository}}
        # lifecycle-policy: deploy-charts/ecr.lifecycle.json
        # repo-policy: deploy-charts/ecr.repo-policy.json
        deleteRepo: false

inputs:
  aws-region:
    description: 'AWS region'
    required: true
    default: 'us-east-1'
  aws-access-key-id:
    description: 'AWS access key' 
    required: true
  aws-secret-access-key:
    description: 'AWS secret Key'
    required: true
  ecr-repository:
    description: 'ECR repository'
    required: true
    default: '869227219142.dkr.ecr.us-east-1.amazonaws.com'
